apiVersion: v1
kind: Service
metadata:
  name: kafkabroker
  labels:
    app: kafkabroker
spec:
  ports:
    - port: 9092
      name: plaintext
    - port: 9999
      name: jmx
  selector:
    app: kafkabroker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
spec:
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: pingack
spec:
  ports:
    - port: 8080
  selector:
    app: pingack
---
apiVersion: v1
kind: Service
metadata:
  name: testing
spec:
  ports:
    - port: 8080
  selector:
    app: testing
---
