apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
spec:
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: testing
          image: ameliasorrenti/testing:v1
          ports:
          - containerPort: 8080
